[package]
name = "system_reporter"
version = "0.3.0"
edition = "2021"

[dependencies]
# Системная информация
sysinfo = "0.30"
whoami = "1.5"
local-ip-address = "0.6"

# Низкоуровневый доступ к Windows
wmi = "0.15"

# Сериализация (JSON)
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Telegram Bot (Асинхронность)
tokio = { version = "1", features = ["full"] }
teloxide = { version = "0.12", features = ["macros"] }
reqwest = { version = "0.11", features = ["multipart"] }

# Обработка ошибок
anyhow = "1.0"
thiserror = "1.0"

# Работа с датой и временем
chrono = "0.4"
